<?php
/*
$sermons[] = array("Sdate" => "",
                 "Title" => "",
		 "Categ" => "",
		 "categ_id" => "",
                 "Descr" => "",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/",
              );
 
$sermons[] = array("Sdate" => "20140816",
                 "Title" => "",
                 "Categ" => "CRU",
		 "categ_id" => "2014081600",
                 "Descr" => "August 2014 Revival Program",
                 "High" => "",
                 "Low" => "",
                 "Audio" => "",
                 "Outline" => "",
              );
*/

// BST, SWS, REV, CRU, RET, YTH
// Define Sermon categories (multi-dimensional) arrays

$sermons[] = array("Sdate" => "20141201",
                 "Title" => "Special Study: The Narrow Way That Leads To Heaven",
                 "Categ" => "BST",
		 "categ_id" => "2014120100",
                 "Descr" => "Weely Bible Study",
                 "High" => "http://s3.amazonaws.com/2014Services/MBS/HQMBS20141201Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/MBS/HQMBS20141201Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/MBS/HQMBS20141201Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS01122014.doc",
              );

$sermons[] = array("Sdate" => "20141130",
                 "Title" => "Compassionate Intercession by Christlike Soul-winners",
                 "Categ" => "SWS",
		 "categ_id" => "2014113000",
                 "Descr" => "Sunday Worship Service",
                 "High" => "http://s3.amazonaws.com/2014Services/SWS/HQSWS20141130Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/SWS/HQSWS20141130Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/SWS/HQSWS20141130Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141124",
                 "Title" => "Special Study: Faith in God’s Spoken Word",
                 "Categ" => "BST",
		 "categ_id" => "2014112400",
                 "Descr" => "Weely Bible Study",
                 "High" => "http://s3.amazonaws.com/2014Services/MBS/HQMBS20141124Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/MBS/HQMBS20141124Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/MBS/HQMBS20141124Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS24112014.doc",
              );

$sermons[] = array("Sdate" => "20141122",
                 "Title" => "The High Calling of Saints in Christ",
                 "Categ" => "CRU",
		 "categ_id" => "2014112100",
                 "Descr" => "November 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/God%20of%20Wonders-November/Messages/The_High_Calling_of_Saints_in_Christ_Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/God%20of%20Wonders-November/Messages/The_High_Calling_of_Saints_in_Christ_Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/God%20of%20Wonders-November/Messages/The_High_Calling_of_Saints_in_Christ_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141122",
                 "Title" => "The Wonders of Christ’s Power",
                 "Categ" => "CRU",
		 "categ_id" => "2014112100",
                 "Descr" => "November 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20Wonders-November/Messages/The_Wonder_of_Christ_Power_Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/God%20of%20Wonders-November/Messages/The_Wonders_of_Christ's_Power_Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/God%20of%20Wonders-November/Messages/The_Wonders_of_Christ's_Power_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141121",
                 "Title" => "The Wonders of Freedom through Christ",
                 "Categ" => "CRU",
		 "categ_id" => "2014112100",
                 "Descr" => "November 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20Wonders-November/Messages/The_Wonders_of_Freedom_through_Christ_Me.mp4",
                 "Low" => "",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20Wonders-November/Messages/The_Wonders_of_Freedom_through_Christ_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141121",
                 "Title" => "Signs and Wonders in His Presence",
                 "Categ" => "CRU",
		 "categ_id" => "2014112100",
                 "Descr" => "November 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20Wonders-November/Messages/Signs_and_Wonders_in_His_Presence_Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20Wonders-November/Messages/Signs_and_Wonders_in_His_Presence_Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20Wonders-November/Messages/Signs_and_Wonders_in_His_Presence.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141120",
                 "Title" => "The Miracle in the Believer’s Decree",
                 "Categ" => "REV",
		 "categ_id" => "2014112000",
                 "Descr" => "Monthly Revival Service",
                 "High" => "http://s3.amazonaws.com/2014Services/THURS/HQTHURS20141120Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/THURS/HQTHURS20141120Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/THURS/HQTHURS20141120Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141117",
                 "Title" => "Special Study: The Dynamics of Irresistible Faith",
                 "Categ" => "BST",
		 "categ_id" => "2014111700",
                 "Descr" => "Weely Bible Study",
                 "High" => "http://s3.amazonaws.com/2014Services/MBS/MBS20141117Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/MBS/MBS20141117Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/MBS/MBS20141117Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS17112014.doc",
              );

$sermons[] = array("Sdate" => "20141110",
                 "Title" => "Special Study: The Destiny of Multitudes in the Popular Way",
                 "Categ" => "BST",
		 "categ_id" => "2014111000",
                 "Descr" => "Weely Bible Study",
                 "High" => "http://s3.amazonaws.com/2014Services/MBS/HQMBS20141110Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/MBS/HQMBS20141110Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/MBS/HQMBS20141110Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS10112014.doc",
              );

$sermons[] = array("Sdate" => "20141103",
                 "Title" => "Special Study: The Universal Principle of a Righteous Life",
		 "Categ" => "BST",
		 "categ_id" => "2014110300",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141103Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141103Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141103Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS03112014.doc",
              );

$sermons[] = array("Sdate" => "20141027",
                 "Title" => "Special Study: Assurance of Answered Prayer for Everyone",
		 "Categ" => "BST",
		 "categ_id" => "2014102700",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141027Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141027Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141027Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS27102014.doc",
              );

$sermons[] = array("Sdate" => "20141026",
                 "Title" => "STS Summary: Conflict between Israel and Benjamin",
                 "Categ" => "SWS",
		 "categ_id" => "2014102600",
                 "Descr" => "Search The Scripture Summary",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20141026Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20141026Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20141026Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141026",
                 "Title" => "The Self-Destruction of a Permissive Nation",
                 "Categ" => "SWS",
		 "categ_id" => "2014102600",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20141026Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20141026Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20141026Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141020",
                 "Title" => "Special Study: Knocking Heaven’s Door until it is Opened",
		 "Categ" => "BST",
		 "categ_id" => "2014102000",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141020Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141020Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141020Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS20102014.doc",
              );

$sermons[] = array("Sdate" => "20141018",
                 "Title" => "The Bride of Christ on Earth",
                 "Categ" => "CRU",
		 "categ_id" => "2014101700",
                 "Descr" => "October 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/The_Bride_of_Christ_on_Earth_Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/The_Bride_of_Christ_on_Earth_Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/The_Bride_of_Christ_on_Earth_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141018",
                 "Title" => "Ever Increasing Faith and Power",
                 "Categ" => "CRU",
		 "categ_id" => "2014101700",
                 "Descr" => "October 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/Ever_Increasing_Faith_and_Power_Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/Ever_Increasing_Faith_and_Power_Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/Ever_Increasing_Faith_and_Power_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141017",
                 "Title" => "The Prophecy of your Miracle Explosion",
                 "Categ" => "CRU",
		 "categ_id" => "2014101700",
                 "Descr" => "October 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/The_Prophecy_of_your_Miracle_Explosion_Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/The_Prophecy_of_your_Miracle_Explosion_Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/The_Prophecy_of_your_Miracle_Explosion_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141017",
                 "Title" => "Power for Explosive Miracle",
                 "Categ" => "CRU",
		 "categ_id" => "2014101700",
                 "Descr" => "October 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/Power_for_Explosive_Miracle_Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/Power_for_Explosive_Miracle_Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20all%20possibilities-October/messages/Power_for_Explosive_Miracle_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141016",
                 "Title" => "The Irresistible Power of Our Incomparable God",
                 "Categ" => "REV",
		 "categ_id" => "2014101600",
                 "Descr" => "Monthly Revival Service",
                 "High" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20141016Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20141016Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20141016Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20141013",
                 "Title" => "Special Study: Christ&rsquo;s Promise for Seeking God by Prayer",
		 "Categ" => "BST",
		 "categ_id" => "2014101300",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141013Me.mp4",
                 "Low" => "",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141013Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS13102014.doc",
              );

$sermons[] = array("Sdate" => "20141006",
                 "Title" => "Special Study: Asking In Prayer with Great Assurance",
		 "Categ" => "BST",
		 "categ_id" => "2014100600",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141006Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141006Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20141006Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS06102014.doc",
              );

$sermons[] = array("Sdate" => "20140929",
                 "Title" => "Special Study: The Necessity of Discernment and Wisdom in Ministry",
		 "Categ" => "BST",
		 "categ_id" => "2014092900",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140929Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140929Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140929Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS29092014.doc",
              );

$sermons[] = array("Sdate" => "20140928",
                 "Title" => "STS Summary: Moral Perversion in Gibeah",
                 "Categ" => "SWS",
		 "categ_id" => "2014092800",
                 "Descr" => "Search The Scripture Summary",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20140928Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20140928Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20140928Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140928",
                 "Title" => "Renewing Our Commitment to God&rsquo;s Forgotten Word",
                 "Categ" => "SWS",
		 "categ_id" => "2014092800",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140928Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140928Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140928Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140922",
                 "Title" => "Special Study: Transparent Holiness before Profitable Ministry",
		 "Categ" => "BST",
		 "categ_id" => "2014092200",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140922Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140922Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140922Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS22092014.doc",
              );

$sermons[] = array("Sdate" => "20140920",
                 "Title" => "Faith in God&rsquo;s Faithfulness",
                 "Categ" => "CRU",
		 "categ_id" => "2014091900",
                 "Descr" => "September 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Recovering%20the%20Lost-September/Messages/Faith%20in%20God%27s%20Faithfulness_Me.mp4",
                 "Low" => "",
                 "Audio" => "",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140919",
                 "Title" => "Extraordinary Wonders from Jesus",
                 "Categ" => "CRU",
		 "categ_id" => "2014091900",
                 "Descr" => "September 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Recovering%20the%20Lost-September/Messages/God%27s%20Explosive%20Power%20TodayMe.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Recovering%20the%20Lost-September/Messages/Extraordinary%20Wonders%20from%20Jesus_Low.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Recovering%20the%20Lost-September/Messages/Extraordinary%20Wonders%20from%20Jesus_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140919",
                 "Title" => "God&rsquo;s Explosive Power Today",
                 "Categ" => "CRU",
		 "categ_id" => "2014091900",
                 "Descr" => "September 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Recovering%20the%20Lost-September/Messages/God%27s%20Explosive%20Power%20TodayMe.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Recovering%20the%20Lost-September/Messages/God%27s%20Explosive%20Power%20TodayLow.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Recovering%20the%20Lost-September/Messages/God%27s%20Explosive%20Power%20TodayEng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140919",
                 "Title" => "My Day of Miracle Explosion",
                 "Categ" => "CRU",
		 "categ_id" => "2014091900",
                 "Descr" => "September 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Recovering%20the%20Lost-September/Messages/YOUR%20DAY%20OF%20MIRACLE%20EXPLOSION%20DAYHigh.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Recovering%20the%20Lost-September/Messages/YOUR%20DAY%20OF%20MIRACLE%20EXPLOSION%20DAYLow.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Recovering%20the%20Lost-September/Messages/YOUR%20DAY%20OF%20MIRACLE%20EXPLOSION%20DAYEng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140918",
                 "Title" => "The Wonder Working Power of the Supernatural Word",
                 "Categ" => "REV",
		 "categ_id" => "2014091800",
                 "Descr" => "Monthly Revival Service",
                 "High" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140918Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140918Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140918Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140915",
                 "Title" => "Study 26: Perseverance in the Evangelistic Ministry",
		 "Categ" => "BST",
		 "categ_id" => "2014091500",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140915Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140915Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140915Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS15092014.doc",
              );

$sermons[] = array("Sdate" => "20140908",
                 "Title" => "Special Study: UnChristlike Judgment Forbidden",
		 "Categ" => "BST",
		 "categ_id" => "2014090800",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140908Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140908Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140908Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS08092014.doc",
              );

$sermons[] = array("Sdate" => "20140901",
                 "Title" => "Special Study: The Gateway to the Spirit-Controlled Life",
		 "Categ" => "BST",
		 "categ_id" => "2014090100",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140901Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140901Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140901Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS01092014.doc",
              );

$sermons[] = array("Sdate" => "20140831",
                 "Title" => "STS Summary: Divine Healing and Health",
                 "Categ" => "SWS",
		 "categ_id" => "2014083100",
                 "Descr" => "Search The Scripture Summary",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20140831Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20140831Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20140831Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140831",
                 "Title" => "Healing and Health for the Whole Man",
                 "Categ" => "SWS",
		 "categ_id" => "2014083100",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140831Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140831Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140831Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140825",
                 "Title" => "Special Study: Caution against Uncharitable Judgement",
		 "Categ" => "BST",
		 "categ_id" => "2014082500",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140825Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140825Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140825Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS25082014.doc",
              );

$sermons[] = array("Sdate" => "20140821",
                 "Title" => "Total healing for the Whole Man",
                 "Categ" => "REV",
		 "categ_id" => "2014082100",
                 "Descr" => "Monthly Revival Service",
                 "High" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140821Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140821Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140821Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140818",
                 "Title" => "Special Study: Consecration and Non-Conformity to this World",
		 "Categ" => "BST",
		 "categ_id" => "2014081800",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140818Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140818Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140818Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS18082014.doc",
              );

$sermons[] = array("Sdate" => "20140817",
                 "Title" => "Collated Testimony / Christ prayer and Intercession for you",
                 "Categ" => "CRU",
		 "categ_id" => "2014081600",
                 "Descr" => "August 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20Wonders-August/messages/Christ%27s_Intercession_and_Prayer_for_You_Me.mp4",
                 "Low" => "",
                 "Audio" => "",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140816",
                 "Title" => "The Prevailing Power of Jesus",
                 "Categ" => "CRU",
		 "categ_id" => "2014081600",
                 "Descr" => "August 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20Wonders-August/messages/The_Prevailing_Power_of_Jesus_Me.mp4",
                 "Low" => "",
                 "Audio" => "",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140816",
                 "Title" => "The Wonder of Taking Back your Inheritance",
                 "Categ" => "CRU",
		 "categ_id" => "2014081600",
                 "Descr" => "August 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20Wonders-August/messages/The_Wonder_of_Taking_Back_your_Inheritance_Me.mp4",
                 "Low" => "",
                 "Audio" => "",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140816",
                 "Title" => "The Great Exchange",
                 "Categ" => "CRU",
		 "categ_id" => "2014081600",
                 "Descr" => "August 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/God%20of%20Wonders-August/messages/The_Great_Exchange_Me.mp4",
                 "Low" => "",
                 "Audio" => "",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140811",
                 "Title" => "Study 25:Transforming the World With Christ&rsquo;s Message",
		 "Categ" => "BST",
		 "categ_id" => "2014081100",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140811Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140811Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140811Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS11082014.doc",
              );

$sermons[] = array("Sdate" => "20140804",
                 "Title" => "Special Study: The Uncommon Christian in the Contemporary World",
		 "Categ" => "BST",
		 "categ_id" => "2014080400",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140804Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140804Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140804Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS04082014.doc",
              );

$sermons[] = array("Sdate" => "20140728",
                 "Title" => "Special Study: Break the Worry Habit: Live One Day at a Time",
		 "Categ" => "BST",
		 "categ_id" => "2014072800",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140728Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140728Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140728Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS28072014.doc",
              );

$sermons[] = array("Sdate" => "20140727",
                 "Title" => "The Fundamental Principles in the Kingdom Life of Faith",
                 "Categ" => "SWS",
		 "categ_id" => "2014072700",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140727Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140727Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140727Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140721",
                 "Title" => "Special Study: Leaving All Our Worries in God&rsquo;s Hands",
		 "Categ" => "BST",
		 "categ_id" => "2014072100",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140721Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140721Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140721Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS14072014.doc",
              );

$sermons[] = array("Sdate" => "20140720",
                 "Title" => "Collated Testimony / The Life Of A Soaring Eagle",
                 "Categ" => "CRU",
		 "categ_id" => "2014071900",
                 "Descr" => "July 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/The_Life_of_a_Soaring_Eagle_Me.wmv",
                 "Low" => "",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/The_Life_of_a_Soaring_Eagle_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140720",
                 "Title" => "Campus: Power through partnership with Christ",
                 "Categ" => "CRU",
		 "categ_id" => "2014071900",
                 "Descr" => "July 2014 Revival Program",
                 "High" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/POWER%20THROUGH%20PARTNERSHIP%20WITH%20CHRISThigh.mp4",
                 "Low" => "",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/POWER%20THROUGH%20PARTNERSHIP%20WITH%20CHRIST.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140719",
                 "Title" => "Peculiar Favour for the Faithful",
                 "Categ" => "CRU",
		 "categ_id" => "2014071900",
                 "Descr" => "July 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/Peculiar_Favour_for_the_Faithful_me.wmv",
                 "Low" => "",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/Peculiar_Favour_for_the_Faithful.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140719",
                 "Title" => "Tarrying For Gods Power Manifestation",
                 "Categ" => "CRU",
		 "categ_id" => "2014071900",
                 "Descr" => "July 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/Tarrying_For_Gods_Power_Manifestation.wmv",
                 "Low" => "",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/Tarrying_For_Gods_Power_Manifestation.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140719",
                 "Title" => "YOUTH: Soaring With the Renewed Eagle",
                 "Categ" => "YTH",
		 "categ_id" => "2014071900",
                 "Descr" => "July 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/Soaring_With_the_Renewed_Eagle_Me.mp4",
                 "Low" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/Soaring%20with%20the%20renewed%20eagle.mp4",
                 "Audio" => "http://s3.amazonaws.com/2014Services/Monthly%20Revival&Miracle/Soaring%20on%20Eagles%20Wing-July/Messages/Soaring_With_the_Renewed_Eagle_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140717",
                 "Title" => "The Key that Opens the Door",
                 "Categ" => "REV",
		 "categ_id" => "2014071700",
                 "Descr" => "Monthly Revival Service",
                 "High" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140717Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140717Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140717Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140714",
                 "Title" => "Special Study: Unlimited Blessings for Christ Indwelt-Believers",
                 "Categ" => "BST",
		 "categ_id" => "2014071400",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140714Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140714Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140714Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS14072014.doc",
              );


$sermons[] = array("Sdate" => "20140707",
                 "Title" => "Special Study: God&rsquo;s Faithfulness Releases us from Worry and Anxiety",
                 "Categ" => "BST",
		 "categ_id" => "2014070700",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140707Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140707Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140707Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS07072014.doc",
              );

$sermons[] = array("Sdate" => "20140630",
                 "Title" => "Special Study: Faith That Banishes Worry and Anxiety",
                 "Categ" => "BST",
		 "categ_id" => "2014063000",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140630Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140630Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140630Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS30062014.doc",
              );

$sermons[] = array("Sdate" => "20140629",
                 "Title" => "The Priority of Selfless Service in Christian Worship",
                 "Categ" => "SWS",
		 "categ_id" => "2014062900",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140629Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140629Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140629Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140623",
                 "Title" => "Special Study: The Blessing of Serving God",
                 "Categ" => "BST",
		 "categ_id" => "2014062300",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140623Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140623Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140623Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS16062014.doc",
              );

$sermons[] = array("Sdate" => "20140622",
                 "Title" => "God&rsquo;s Book in a Believer&rsquo;s Life",
                 "Categ" => "CRU",
		 "categ_id" => "2014062100",
                 "Descr" => "June 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/The%20Yoke%20is%20broken-June/Messages/God%27s_Book_in_a_Believer%E2%80%99s_Life_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/The%20Yoke%20is%20broken-June/Messages/God%27s_Book_in_a_Believer%E2%80%99s_Life_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/The%20Yoke%20is%20broken-June/Messages/God%27s_Book_in_a_Believer%E2%80%99s_Life_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140621",
                 "Title" => "Come, Continue and Conquer",
                 "Categ" => "CRU",
		 "categ_id" => "2014062100",
                 "Descr" => "June 2014 Revival Program",
                 "High" => "http://goo.gl/hI9aG3",
                 "Low" => "http://goo.gl/RLQ3gb",
                 "Audio" => "http://goo.gl/fPTF0c",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140621",
                 "Title" => "Jesus the Unforgettable Miracle Worker",
                 "Categ" => "CRU",
		 "categ_id" => "2014062100",
                 "Descr" => "June 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/The%20Yoke%20is%20broken-June/Messages/Jesus_the_Unforgettable_Miracle_Worker_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/The%20Yoke%20is%20broken-June/Messages/Jesus_the_Unforgettable_Miracle_Worker_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/The%20Yoke%20is%20broken-June/Messages/Jesus_the_Unforgettable_Miracle_Worker_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140621",
                 "Title" => "Christ&rsquo;s Great Invitation",
                 "Categ" => "CRU",
		 "categ_id" => "2014062100",
                 "Descr" => "June 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/The%20Yoke%20is%20broken-June/Messages/Christ_Great_Invitation_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/The%20Yoke%20is%20broken-June/Messages/Christ_Great_Invitation_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/The%20Yoke%20is%20broken-June/Messages/Christ_Great_Invitation_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140619",
                 "Title" => "The Lord my Security",
                 "Categ" => "REV",
		 "categ_id" => "2014061900",
                 "Descr" => "Monthly Revival Service",
                 "High" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140619Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140619Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140619Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140616",
                 "Title" => "Special Study: Antidote for Worry and Anxiety",
                 "Categ" => "BST",
		 "categ_id" => "2014061600",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140616Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140616Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140616Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS16062014.doc",
              );

$sermons[] = array("Sdate" => "20140602",
                 "Title" => "Special Study: Undivided Loyalty in Serving God",
                 "Categ" => "BST",
		 "categ_id" => "2014060200",
                 "Descr" => "Weekly Bible Study",
                 "High" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140602Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140602Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/MBS/HQMBS20140602Eng.mp3",
                 "Outline" => "http://s3.amazonaws.com/MBSoutlines/2014/MBS02062014.doc",
              );

$sermons[] = array("Sdate" => "20140525",
                 "Title" => "The Mystery of the Indwelling Christ",
                 "Categ" => "SWS",
		 "categ_id" => "2014052500",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140525Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140525Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140525Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140518",
                 "Title" => "Forward, Onward, Upward for Greater Things",
                 "Categ" => "CRU",
		 "categ_id" => "2014051700",
                 "Descr" => "May 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/Forward_Onward_Upward_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/Forward_Onward_Upward_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/Forward_Onward_Upward.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140517",
                 "Title" => "God&rsquo;s Inseparable Blessing",
                 "Categ" => "CRU",
		 "categ_id" => "2014051700",
                 "Descr" => "May 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/God%27s_Inseparable_Blessing_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/God%27s_Inseparable_Blessing_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/God%27s_Inseparable_Blessing.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140517",
                 "Title" => "Jesus the Unchangeable Miracle Worker",
                 "Categ" => "CRU",
		 "categ_id" => "2014051700",
                 "Descr" => "May 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/Jesus_the_Unchangeable_Miracle_Worker_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/Jesus_the_Unchangeable_Miracle_Worker_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/Jesus_the_Unchangeable_Miracle_Worker.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140517",
                 "Title" => "Christ&rsquo;s Irresistible Invitation",
                 "Categ" => "CRU",
		 "categ_id" => "2014051700",
                 "Descr" => "May 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/Christ%27s_Irresistible_Invitation_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/Christ%27s_Irresistible_Invitation_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Binding%20the%20Strong%20Man-May/Messages/Christ%27s_Irresistible_Invitation.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140515",
                 "Title" => "Command and Let the Mountains Move",
                 "Categ" => "REV",
		 "categ_id" => "2014051500",
                 "Descr" => "Monthly Revival Service",
                 "High" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140515Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140515Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/THURS/HQTHURS20140515Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140427",
                 "Title" => "Arise, Go up to Bethel",
                 "Categ" => "SWS",
		 "categ_id" => "2014042700",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140427Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140427Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140427Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140420",
                 "Title" => "Reigning Through the Victory of Jesus",
                 "Categ" => "CRU",
		 "categ_id" => "2014041900",
                 "Descr" => "April 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Destined%20to%20Win-April/Messages/Reigning%20through%20the%20Victory%20of%20Jesus.mp4",
                 "Low" => "",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Destined%20to%20Win-April/Messages/Reigning%20through%20the%20Victory%20of%20Jesus.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140419",
                 "Title" => "Face to Face with Power Unlimited",
                 "Categ" => "CRU",
		 "categ_id" => "2014041900",
                 "Descr" => "April 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Destined%20to%20Win-April/Messages/Face%20to%20face%20with%20Power%20unlimited.mp4",
                 "Low" => "",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Destined%20to%20Win-April/Messages/Face%20to%20face%20with%20Power%20unlimited.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140419",
                 "Title" => "Face to Face with the Almighty",
                 "Categ" => "CRU",
		 "categ_id" => "2014041900",
                 "Descr" => "April 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Destined%20to%20Win-April/Messages/Face%20to%20face%20with%20the%20Almighty.mp4",
                 "Low" => "http://s3.amazonaws.com/2013Services/Files/Monthly%20Revival%26Miracle/F2F%20with%20the%20God%20of%20Miracle-September/Messages/Face%20to%20Face%20with%20the%20Almighty_Low.wmv",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Destined%20to%20Win-April/Messages/Face%20to%20face%20with%20the%20Almighty.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140330",
                 "Title" => "The Powerful Wonder-Working Truth",
                 "Categ" => "SWS",
		 "categ_id" => "2014033000",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140330Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140330Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140330Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140330",
                 "Title" => "STS Summary: Jephthah&rsquo;s Vow and Victory over Ammon",
                 "Categ" => "SWS",
		 "categ_id" => "2014033000",
                 "Descr" => "Search The Scripture Summary",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20140330Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20140330Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSTS20140330Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140316",
                 "Title" => "Collated Testimony/The Power of a Radiant Life",
                 "Categ" => "CRU",
		 "categ_id" => "2014031500",
                 "Descr" => "March 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/The_Power_of_a_Radiant_Life_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/The_Power_of_a_Radiant_Life_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/The_Power_of_a_Radiant_Life.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140315",
                 "Title" => "Jesus the Life Changer",
                 "Categ" => "CRU",
		 "categ_id" => "2014031500",
                 "Descr" => "March 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/Jesus_the_Life_Changer_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/Jesus_the_Life_Changer_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/Jesus_the_Life_Changer.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140315",
                 "Title" => "Receiving Miracles through the Words of Christ",
                 "Categ" => "CRU",
		 "categ_id" => "2014031500",
                 "Descr" => "March 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/Receiving_Miracles_through_the_Words_of_Christ_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/Receiving_Miracles_through_the_Words_of_Christ_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/Receiving_Miracles_through_the_Words_of_Christ.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140315",
                 "Title" => "Great Miracles for True Worshipers",
                 "Categ" => "CRU",
		 "categ_id" => "2014031500",
                 "Descr" => "March 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/Great_Miracles_for_True_Worshipers_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/Great_Miracles_for_True_Worshipers_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Go%20Up%20Higher-March/Messages/Great_Miracles_for_True_Worshipers.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140223",
                 "Title" => "Believers Consecration and Non Conformity to the World",
                 "Categ" => "SWS",
		 "categ_id" => "2014022300",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140223Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140223Low.wmv",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140223Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140216",
                 "Title" => "The Dominant Faith of Steadfast Believers",
                 "Categ" => "CRU",
		 "categ_id" => "2014021500",
                 "Descr" => "February 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/The_Dominant_Faith_of_Steadfast_Believers_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/The_Dominant_Faith_of_Steadfast_Believers_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/The_Dominant_Faith_of_Steadfast_Believers_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140215",
                 "Title" => "Looking Unto Jesus for Healing",
                 "Categ" => "CRU",
		 "categ_id" => "2014021500",
                 "Descr" => "February 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/Looking_Unto_Jesus_for_Healing_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/Looking_Unto_Jesus_for_Healing_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/Looking_Unto_Jesus_for_Healing_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140215",
                 "Title" => "Expect Your Miracle Tonight",
                 "Categ" => "CRU",
		 "categ_id" => "2014021500",
                 "Descr" => "February 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/Expect_Your_Miracle_Tonight_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/Expect_Your_Miracle_Tonight_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/Expect_Your_Miracle_Tonight_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140215",
                 "Title" => "Spectacular Miracle through Divine Encounter",
                 "Categ" => "CRU",
		 "categ_id" => "2014021500",
                 "Descr" => "February 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/Spectacular_Miracle_through_Divine_Encounter_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/Spectacular_Miracle_through_Divine_Encounter_Low.mp4",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Connecting%20with%20the%20God%20of%20Power-Feb/messages/Spectacular_Miracle_through_Divine_Encounter_Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140126",
                 "Title" => "Passion for Progress in the New Year",
                 "Categ" => "SWS",
		 "categ_id" => "2014012600",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140126Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140126Low.wmv",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140126Eng.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140119",
                 "Title" => "New Progress and Partnership in the New Year",
                 "Categ" => "CRU",
		 "categ_id" => "2014011800",
                 "Descr" => "January 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/New_Progress_and_Patnership_in_The_New_Year_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/New_Progress_and_Patnership_in_The_New_Year.wmv",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/New_Progress_and_Patnership_in_The_New_Year.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140119",
                 "Title" => "Believer&rsquo;s Abiding Faith in Jehovah-Jireh",
                 "Categ" => "CRU",
		 "categ_id" => "2014011800",
                 "Descr" => "January 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/Believer%E2%80%99s_Abiding_Faith_in_Jehovah-Jireh_me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/Believer%E2%80%99s_Abiding_Faith_in_Jehovah-Jireh.wmv",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/Believer%E2%80%99s_Abiding_Faith_in_Jehovah-Jireh.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140118",
                 "Title" => "Walking In the Part of Miracles and Wonders",
                 "Categ" => "CRU",
		 "categ_id" => "2014011800",
                 "Descr" => "January 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/Walking_in_the_Part_of_Miracles_and_Wonders_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/Walking_in_the_Part_of_Miracles_and_Wonders.wmv",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/Walking_in_the_Part_of_Miracles_and_Wonders.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140118",
                 "Title" => "The Eternal Defeat of the Ancient Adversary",
                 "Categ" => "CRU",
		 "categ_id" => "2014011800",
                 "Descr" => "January 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/The_Eternal_Defeat_of_the_Ancient_Adversary_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/The_Eternal_Defeat_of_the_Ancient_Adversary.wmv",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/The_Eternal_Defeat_of_the_Ancient_Adversary.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140118",
                 "Title" => "In the Beginning, God",
                 "Categ" => "CRU",
		 "categ_id" => "2014011800",
                 "Descr" => "January 2014 Revival Program",
                 "High" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/In_the_Begining%2C_God_Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/In_the_Begining%2C_God.wmv",
                 "Audio" => "https://s3.amazonaws.com/2014Services/Monthly%20Revival%26Miracle/Supernatural%20Strength-Jan/message/In_the_Begining%2C_God.mp3",
                 "Outline" => "",
              );

$sermons[] = array("Sdate" => "20140105",
                 "Title" => "Preparation for a Life-time of Wonder",
                 "Categ" => "SWS",
		 "categ_id" => "2014010500",
                 "Descr" => "Sunday Worship Service",
                 "High" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140105Me.mp4",
                 "Low" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140105Low.wmv",
                 "Audio" => "https://s3.amazonaws.com/2014Services/SWS/HQSWS20140105Eng.mp3",
                 "Outline" => "",
              );

?>
